# Generated by Django 6.0.2 on 2026-02-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol_api', '0003_branch_latitude_branch_longitude_alter_branch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='patrol_api.branch'),
        ),
    ]
